version: "3.9"
services:
  postgres:
    image: postgres:13.3
    ports:
      - "5432:5432"
    env_file:
      - .env
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env