GET http://localhost:8080/pets

###
GET http://localhost:8080/pets/3

###
POST http://localhost:8080/pets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTQwMjE4MDB9.81VOIdqQvIQJq37LiZN-0NxWFKhYQjBT7FEstl4bOuE

{
    "name": "Bob",
    "ownerId": 1,
    "kind": "Dog",
    "breed": "Labrador",
    "birthDate": "2022-08-12"
}

###
PUT http://localhost:8080/pets/3

{
    "name": "Barsique 2",
    "ownerName": "Ivan",
    "kind": "Dog",
    "breed": "Labrador",
    "birthDate": "2022-02-24"
}

###
DELETE http://localhost:8080/pets/1

###
GET http://localhost:8080/sessions

###
POST http://localhost:8080/sessions

{
    "petId": 2,
    "sitterId": 1,
    "startDate": "2022-02-24T00:00:00Z",
    "endDate": "2022-02-24T00:20:00Z"
}

###
POST http://localhost:8080/users

{
    "name": "Ivan",
    "phoneNumber": "+380991334803"
}
###
GET http://localhost:8080/users/1

###
GET http://localhost:8080/users

###
POST http://localhost:8080/auth